# Generated by Django 5.2.12 on 2026-03-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_booking_seat_booking_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('PENDING_VERIFICATION', 'Pending Verification')], default='PENDING_PAYMENT', max_length=25),
        ),
    ]
